### PR TITLE
Introduces a sytem for playing sounds

### PR DESCRIPTION
**Pull request by NancokPS2**
Adds the SoundManager class with it's own documentation (under the F1 menu in the editor).  
  
It works by keeping an Array of AudioStreamPlayers of the 3 available types (non-positional, 2D and 3D) that are used whenever they are available. If none are, more are added on demand up to a configurable limit (16 by default).  
    
These players can be configured using SoundManager.AudioPlayerSettings using a factory-pattern as shown in the documentation.  

**NOTE:** ~gdformat does not understand "static var" declarations and raises an error in SoundManager.gd, this is harmless and i already reported it to the gdtoolkit repo.~ Fixed

### CODE REVIEW

**Comment by NancokPS2** [comment]
Closes #160

**Comment by NancokPS2** [comment]
According to the devs of gdtoolkit, this has been fixed in their "master" branch and said fix will be rolled out in the next release. We can swap to the build in the "master" branch to receive the fix now.

**Comment by NancokPS2** [comment]
Now that i look at the way it works, it could be further simplified to not require a new subclass just for storing settings. Setting as draft until i get around to doing it.

**Comment by NancokPS2** [comment]
Nevermind, it would require more spaghetti

**Comment by NancokPS2** [comment]
👌 (?)

**Comment by jonathaneeckhout** [comment]
When running the game I get the error:
Invalid set index 'parent' (on base: 'Node (SoundManager)') with value of type 'Node (jdungeon.gd)'.

```
func _ready():
	uuid_util = load("res://scripts/uuid/uuid.gd").new()

	audio.parent = self <-- error on this line
	audio.main_instance = audio
```

**Pull request merged**
