### PR TITLE
Changed how entities collide with each other (fixes players pushing each other)

### PR DESCRIPTION
**Pull request by NancokPS2**
Players are stopped by NPCs and enemies.   
Enemies are stopped by NPCs and players.  
NPCs are not stopped by anything.
They all still collide with the world.  
  
Entities no longer exist on the J.PHYSICS_LAYER_WORLD and merely use their mask to collide with it.      
    
It was necessary to add the ability for the ConditionLeaf "IsInCombat" to filter targets by type instead of choosing ANYTHING entering their area. (it caused enemies to attack each other lol)  

Tests performed:  
- Try to aggro multiple enemies, they will not block each other and will just walk trough. They will still collide with the player.  
- Attempt to get in the path of a moving NPC, the NPC just pushes you aside

### CODE REVIEW

**Comment by NancokPS2** [comment]
Closes #103

**Comment by jonathaneeckhout** [comment]
Will test it functionality wise.

The pipeline is failing due to not conform with code styling:
```
Some files in specified directories are not well-formatted. Please run 'gdformat' to fix them:
would reformat scripts/classes/JBody2D.gd
1 file would be reformatted, 0 files would be left unchanged.
Error: Process completed with exit code 1.
```

gdformat is a tool from gdtoolkit

**Comment by NancokPS2** [comment]
How do fix this exactly? is there a git command or some more detailed message for the error?

**Comment by NancokPS2** [comment]
Found it and isntalled it (might want to add it to the contributions guideline)  
It was just some redundant line breaks, should be fine now.

**Comment by jonathaneeckhout** [comment]
> Found it and isntalled it (might want to add it to the contributions guideline) It was just some redundant line breaks, should be fine now.

It's already there:
```
[Use Code Style for Scripts](https://github.com/jonathaneeckhout/jdungeon/blob/main/CONTRIBUTING.md#use-code-style-for-scripts)
JDungeon uses the code style defined by [GDtoolkit](https://pypi.org/project/gdtoolkit/). Use this tool to format your code. It can also be added as a plugin to VSCode.
```

**Comment by NancokPS2** [comment]
Oh, my bad.  
I just checked the guidelines and missed it somehow.

**Pull request merged**
