### PR TITLE
Options menu upgrade

### PR DESCRIPTION
**Pull request by NancokPS2**
- Input names no longer show "(Physical)"   
- The server no longer loads local settings (All server relevant settings should go in the ENV system)  
- Added ShaderMaterial-based class that automatically chooses a colorblindness shader based on settings
  
- Added several options  
  - Set shadow filtering and resolution quality  
  - Set anti aliasing  
  - Change tooltip delay
  - Change language (merely adds support for changing language should a user add their own, a disclaimer is included in the tooltip)  
  - Set global illumination from certain, costly nodes to half resolution  
  - Set maximum FPS and VSync  
  - Enable or disable full screen  
  - Hotkeys to hide or show the chat/GUI independently
  - Button to open the User Data folder
  - Support for custom translations  
  - Colourblind filter option (no implementation yet)
  

I'm not that experienced with graphical options, so i am not sure if the tooltips for them are completely accurate.   
Also some of them have no effect at the moment, since we don't actually use lighting nor 3D for much of anything.  
    
Tested by entering the options menu in-game and playing with the settings. All of them do as they say and are saved locally.  
  
(Crossed out items have been added)  

Considerations for future PRs:  
- Mono/Stereo audio toggle or slider (why do games not have this option anymore?)
- Texture/Decal/Projector filter default quality   
- ~~Button to open the local save folder~~    
- ~~Actual functionality for importing languages during run-time.~~
- Audio output latency (lowering this can cause audio crackling and performance loss in slower hardware)  
- Video delay compensation (for people playing on high latency monitors, like a TV)  
- Renderer selection (this is already handled by Godot and there's little reason to change it, but could help with edge cases of incompatibility)  
- Max renderable objects/lights (only affects Compatibility mode)
- Controller support  
  
From Kashan's  
- Separate audio sliders for sound effects, music and dialogue (if there is any)
- Subtitle options for opacity of text box or font
- ~~Colorblind/Accessibility options (longer term project/goal probably)~~ (somewhat done)
- ~~Toggle Hud (screenshot mode)~~
- Option to disable chat completely (multiplayer games and gamers...)
- Toggle damage # pop ups (or some category of 'pop ups') (edited)
- Cussing toggle (this is a family friendly minecraft server)

### CODE REVIEW

**Comment by jonathaneeckhout** [comment]
@NancokPS2 can you rebase?

Thx

**Comment by NancokPS2** [comment]
> @NancokPS2 can you rebase?
> 
> Thx

Done, there where two conflicts on a single file and that was that, some divine intervention right there.

**Comment by jonathaneeckhout** [comment]
Thanks for your PR again.

Issues:
- when I launch the game, it is at full screen, when I open the game menu and open the options menu, the game's window size is shrunk. It seems to be because the fullscreen option is false

Question:
- what does the tooltip delay do?

**Comment by NancokPS2** [comment]
I forgot to run the config load during the function dedicated to it.  
The tooltip is what appears whenever you hover over a Control node with the mouse cursor, the delay controls how long it takes for the tooltip to appear once hovered.  
However, it seems like Godot is ignoring the setting entirely, even for built-in stuff like the editor's UI.  
It seems like an engine bug that may be fixed by 4.2

**Comment by NancokPS2** [comment]
Tooltip delay affects the time it takes for a tooltip to appear whenever you hover over a Control node (IF they have one set at all, most settings do)  
However, it is currently impossible to affect it during runtime so the setting doesn't do anything (i removed it until they give an alternative)  
  
I fixed the oddities by having the settings no longer load with the menu and do so at game-start instead.

**Comment by jonathaneeckhout** [comment]
Tested it and works nice.

Could you change 1 more thing?

Can the full screen be true as default? This is the intended size the game should be played in.

If you fix this, I will merge it.

thx

**Comment by jonathaneeckhout** [comment]
Correcting myself:

Fullscreen should not be the default setting. 

I've corrected the behavior so that at default if the fullscreen is not checked the window is not reloaded to windowed mode, which made the game flicker.

I also fixed a naming.

Will merge now

**Pull request merged**
